# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiation',
            name='feedback_of',
        ),
    ]
