# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_initiation_feedback_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiation',
            name='feedback_of',
            field=models.CharField(default='fe', max_length=8),
            preserve_default=False,
        ),
    ]
